#!/usr/bin/env python
#
# handle build in this directory.
#------------------------------------------------------------------------------
import os
Import('murat_env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
def local_build():
    local_env = murat_env.Clone()

    rootlibs = local_env['ROOTLIBS']
    if ( not ("Minuit" in rootlibs)): rootlibs.insert(rootlibs.index("Physics")+1,"Minuit");

    debug=False;
    helper = stntuple_helper(local_env,debug);


    helper.handle_dictionaries(suffix=".h");

    list_of_cc_files = Glob('*.cc',strings=True);
    skip_list        = []
    libs             = rootlibs

    helper.build_libs(list_of_cc_files,skip_list,libs);
# ------------------------------------------------------------------------------
local_build();

