#
# Macro file for setting up the graphics scene and the verbosity level: xy view
#
#
# $Id: visxy.mac,v 1.1 2013/06/07 13:54:22 murat Exp $
# $Author: murat $
# $Date: 2013/06/07 13:54:22 $
#
# Original author Rob Kutschke

/control/verbose 0
/run/verbose 0
/vis/open OGLI 200x200-0+0
/vis/viewer/set/viewpointThetaPhi 0 30 deg
/vis/viewer/zoom 2.0
/vis/disable
/vis/scene/create
/vis/scene/add/volume CalorimeterMother
/vis/scene/add/trajectories
/vis/sceneHandler/attach
/vis/scene/endOfEventAction refresh
/vis/enable 

# Do NOT issue the /run/beamon command
