#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os
Import('murat_env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
def local_build():
    local_env = murat_env.Clone()

    rootlibs = local_env['ROOTLIBS']

    if ( not ("EG" in rootlibs)): rootlibs.insert(rootlibs.index("Physics")+1,"EG");

    helper = stntuple_helper(local_env);

    helper.handle_dictionaries();

    skip_list        = []
    libs             = [ 'murat_obj', 'murat_mclimit', 'Stntuple_val', rootlibs ]
    list_of_cc_files = Glob('*.cc',strings=True);

    helper.build_libs(list_of_cc_files,skip_list,libs);
# ------------------------------------------------------------------------------
local_build();

