///////////////////////////////////////////////////////////////////////////////
// 
///////////////////////////////////////////////////////////////////////////////
#include "murat/ana/scripts/modules.hh"

def_name track_0010 ("track_ana");
def_name track_0020 ("val_cpr");
def_name track_0050 ("track_ana_tandip_12");
def_name track_0060 ("track_debug_tandip_12");
def_name track_0070 ("track_ana_dem");
def_name track_00701("track_ana_dep");
def_name track_00702("track_ana_dpp");
def_name track_0073 ("track_ana_dmm");
def_name track_0080 ("track_ana_ump");
def_name track_0081 ("track_ana_umm");
def_name track_0110 ("track_ana_nocorr");

def_name track_0510 ("track_comp");
def_name track_0511 ("track_comp_old");
def_name track_0512 ("track_comp_debug");
def_name track_0520 ("track_comp_mva");
def_name track_0530 ("track_comp_use_mva");

def_name track_100  ("track_anaB");
///////////////////////////////////////////////////////////////////////////////

//-----------------------------------------------------------------------------
void  track_ana(const char* TrackBlockName = "TrackBlockPar", int PdgCode = 11, int MCProcessCode = 2, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  

  murat::m_trk->SetTrackBlockName(TrackBlockName);
  murat::m_trk->SetPDGCode      (PdgCode);
  murat::m_trk->SetMCProcessCode(MCProcessCode);

  if (DebugBit >= 0) {
    murat::m_trk->SetDebugBit(DebugBit,1);
  }
}

//-----------------------------------------------------------------------------
void  track_ana_nocorr(int PdgCode = 11, int MCProcessCode = 2, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetPDGCode      (PdgCode);
  murat::m_trk->SetMCProcessCode(MCProcessCode);
  murat::m_trk->SetApplyCorrections(0);
  if (DebugBit >= 0) {
    murat::m_trk->SetDebugBit(DebugBit,1);
  }
}

//-----------------------------------------------------------------------------
void  track_ana_dmm(int PdgCode = 13) {
//-----------------------------------------------------------------------------
// configure analysis module to handle signal muons reconstructed as muons
// generated by SingleParticleReactionGun
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockDmm");
  murat::m_trk->SetPDGCode(PdgCode);
  murat::m_trk->SetDirection(1);
  murat::m_trk->SetMCProcessCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_dem(int PdgCode = 11) {
//-----------------------------------------------------------------------------
// configure analysis module to handle signal muons reconstructed as muons
// generated by SingleParticleReactionGun
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockDem");
  murat::m_trk->SetTrackStrawHitBlockName("TrackHitBlockDem");
  murat::m_trk->SetPDGCode(PdgCode);
  murat::m_trk->SetDirection(1);
  murat::m_trk->SetMCProcessCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_dep(int PdgCode = 12) {
//-----------------------------------------------------------------------------
// configure analysis module to handle positrons 
// generated by SingleParticleReactionGun (28)
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockDep");
  murat::m_trk->SetTrackStrawHitBlockName("TrackHitBlockDep");
  murat::m_trk->SetPDGCode(PdgCode);
  murat::m_trk->SetDirection(1);
  murat::m_trk->SetMCProcessCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_dpp() {
//-----------------------------------------------------------------------------
// configure analysis module to handle positrons 
// generated by SingleParticleReactionGun (28)
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockDpp");
  murat::m_trk->SetTrackStrawHitBlockName("TrackHitBlockDpp");
  murat::m_trk->SetPDGCode(2212);
  murat::m_trk->SetDirection(1);
  murat::m_trk->SetMCProcessCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_ump() {
//-----------------------------------------------------------------------------
// configure analysis module to handle signal muons reconstructed as muons
// generated by SingleParticleReactionGun
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockUmp");
  murat::m_trk->SetPDGCode(-13);
  murat::m_trk->SetDirection(-1);
  murat::m_trk->SetMCProcessCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_umm() {
//-----------------------------------------------------------------------------
// configure analysis module to handle signal muons reconstructed as muons
// generated by SingleParticleReactionGun
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockUmm");
  murat::m_trk->SetPDGCode(13);
  murat::m_trk->SetDirection(-1);
  murat::m_trk->SetMCProcessCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_tandip_12(int MCProcessCode = 2) {
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->GetTrackID(0)->SetMinTanDip(1.);
  murat::m_trk->GetTrackID(0)->SetMaxTanDip(2.);
}

//-----------------------------------------------------------------------------
void  val_cpr(int Bit = -1) {
//-----------------------------------------------------------------------------
// configure analysis modules
//-----------------------------------------------------------------------------
  m_vcpr = (TValCalPatRecModule*) g.x->AddModule("TValCalPatRecModule",0);  

  if (Bit != -1) {
    m_vcpr->SetDebugBit(Bit,1);
  }
}


//-----------------------------------------------------------------------------
void  track_debug_tandip_12(int Bit, int MCProcessCode = 2) {
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->GetTrackID(0)->SetMinTanDip(1.);
  murat::m_trk->GetTrackID(0)->SetMaxTanDip(2.);
  murat::m_trk->SetDebugBit(Bit,1);
}

//-----------------------------------------------------------------------------
// MCProcessCode= 2:ConversionElectronGun 28:ParticleGun
//-----------------------------------------------------------------------------
void  track_comp(const char* TrackBlockName = "TrackBlockPar", int PDGCode=11, int MCProcessCode=28, 
		 int DebugBit = -1, double XMin=1,double XMax = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  

  murat::m_tcm->SetTrackBlockName(0,TrackBlockName);
  murat::m_tcm->SetPDGCode       (PDGCode);
  murat::m_tcm->SetMCProcessCode (MCProcessCode);

  if (DebugBit >= 0) {
    murat::m_tcm->SetDebugBit(DebugBit,1);
    if (XMin < XMax) murat::m_tcm->SetDebugCut(DebugBit,XMin,XMax);
  }
}

//-----------------------------------------------------------------------------
// debug: do not fill histograms, force the debug bit to be defined
//-----------------------------------------------------------------------------
void  track_comp_debug(int PDGCode=11, int MCProcessCode=28, int DebugBit=14) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetPDGCode      (PDGCode);
  murat::m_tcm->SetMCProcessCode(MCProcessCode);
  murat::m_tcm->SetDebugBit(DebugBit,1);
  murat::m_tcm->GetAna()->SetNEventsToReport(50000);
}

//-----------------------------------------------------------------------------
// configure analysis module to write TMVA training trees
// MCProcessCode= 2:ConversionElectronGun 28:ParticleGun 7:dioTail
// TrkRrecoAlg = 0:PAR , 1:DAR
// by default, the PDGCode and the MCProcessCode are read from the catalog
//-----------------------------------------------------------------------------
void  track_comp_mva(int TrkRecoAlg = 0, int PDGCode=0, int MCProcessCode=-1, int DebugBit = -1) {
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  

  if (PDGCode       != 0) murat::m_tcm->SetPDGCode      (PDGCode);
  if (MCProcessCode >  0) murat::m_tcm->SetMCProcessCode(MCProcessCode);

  murat::m_tcm->SetWriteMvaTree(TrkRecoAlg);

  if (DebugBit >= 0) murat::m_tcm->SetDebugBit(DebugBit,1);
}

//-----------------------------------------------------------------------------
// MCProcessCode= 2:ConversionElectronGun 28:ParticleGun
// MVAType : 
// ---------
// by default, PDGCode and MCProcessID are picked from the catalog
//-----------------------------------------------------------------------------
void  track_comp_use_mva(int PARTrainingCode =   -1, 
			 int DARTrainingCode = 1070, 
			 int PDGCode=11, int MCProcessCode=28, 
			 int DebugBit = -1, double XMin=1,double XMax = -1) {
//-----------------------------------------------------------------------------
// configure analysis module to use TMVA training trees
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetPDGCode      (11);
  murat::m_tcm->SetMCProcessCode(MCProcessCode);

  if (PARTrainingCode >= 0) {
    int charge_mode = PARTrainingCode/100;
    if   (charge_mode == 0) murat::m_tcm->SetTrqMVA(0,"fele2s51b1",PARTrainingCode);  // negative
    else                    murat::m_tcm->SetTrqMVA(0,"fpos2s51b1",PARTrainingCode);  // positive
  }
  if (DARTrainingCode >= 0) {
    int charge_mode = DARTrainingCode/100;
    if   (charge_mode == 0) murat::m_tcm->SetTrqMVA(1,"fele2s51b1",DARTrainingCode);  // negative
    else                    murat::m_tcm->SetTrqMVA(1,"fpos2s51b1",DARTrainingCode);  // positive
  }

  if (DebugBit >= 0) {
    murat::m_tcm->SetDebugBit(DebugBit,1);
    if (XMin < XMax) murat::m_tcm->SetDebugCut(DebugBit,XMin,XMax);
  }
}


//-----------------------------------------------------------------------------
//
//-----------------------------------------------------------------------------
void  rmc_ana(double KMax = 90, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module to write TMVA training trees
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetPDGCode      (-11);
  murat::m_tcm->SetMCProcessCode(41);

  murat::m_tcm->SetKMaxRMC(KMax);

  if (DebugBit >= 0) murat::m_tcm->SetDebugBit(DebugBit,1);
}

