///////////////////////////////////////////////////////////////////////////////
// 
///////////////////////////////////////////////////////////////////////////////
#include "murat/ana/scripts/modules.hh"

def_name track_0010 ("track_ana");
def_name track_0020 ("val_cpr");
def_name track_0050 ("track_ana_tandip_12");
def_name track_0060 ("track_debug_tandip_12");
def_name track_0070 ("track_ana_dem");
def_name track_00701("track_ana_dep");
def_name track_00702("track_ana_dpp");
def_name track_0071 ("track_ana_tpr");
def_name track_0072 ("track_ana_cpr");
def_name track_0073 ("track_ana_dmm");
def_name track_0080 ("track_ana_ump");
def_name track_0081 ("track_ana_umm");
def_name track_0110 ("track_ana_nocorr");

def_name track_0510 ("track_comp");
def_name track_0511 ("track_comp_old");
def_name track_0512 ("track_comp_debug");
def_name track_0520 ("track_comp_tmva");
def_name track_0530 ("track_comp_use_mva");

def_name track_100  ("track_anaB");
///////////////////////////////////////////////////////////////////////////////

//-----------------------------------------------------------------------------
void  track_ana(int PdgCode = 11, int GeneratorCode = 2, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetPdgCode      (PdgCode);
  murat::m_trk->SetGeneratorCode(GeneratorCode);
  if (DebugBit >= 0) {
    murat::m_trk->SetDebugBit(DebugBit,1);
  }
}

//-----------------------------------------------------------------------------
void  track_ana_tpr(int PdgCode = 11, int GeneratorCode = 2, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);
  murat::m_trk->SetPdgCode      (PdgCode);
  murat::m_trk->SetGeneratorCode(GeneratorCode);
  murat::m_trk->SetTrackBlockName("TrkPatRec");
  if (DebugBit >= 0) {
    murat::m_trk->SetDebugBit(DebugBit,1);
  }
}

//-----------------------------------------------------------------------------
void  track_ana_cpr(int PdgCode = 11, int GeneratorCode = 2, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);
  murat::m_trk->SetPdgCode      (PdgCode);
  murat::m_trk->SetGeneratorCode(GeneratorCode);
  murat::m_trk->SetTrackBlockName("CalPatRec");
  if (DebugBit >= 0) {
    murat::m_trk->SetDebugBit(DebugBit,1);
  }
}

//-----------------------------------------------------------------------------
void  track_ana_nocorr(int PdgCode = 11, int GeneratorCode = 2, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetPdgCode      (PdgCode);
  murat::m_trk->SetGeneratorCode(GeneratorCode);
  murat::m_trk->SetApplyCorrections(0);
  if (DebugBit >= 0) {
    murat::m_trk->SetDebugBit(DebugBit,1);
  }
}

//-----------------------------------------------------------------------------
void  track_ana_dmm(int PdgCode = 13) {
//-----------------------------------------------------------------------------
// configure analysis module to handle signal muons reconstructed as muons
// generated by SingleParticleReactionGun
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockDmm");
  murat::m_trk->SetPdgCode(PdgCode);
  murat::m_trk->SetDirection(1);
  murat::m_trk->SetGeneratorCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_dem(int PdgCode = 11) {
//-----------------------------------------------------------------------------
// configure analysis module to handle signal muons reconstructed as muons
// generated by SingleParticleReactionGun
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockDem");
  murat::m_trk->SetTrackStrawHitBlockName("TrackHitBlockDem");
  murat::m_trk->SetPdgCode(PdgCode);
  murat::m_trk->SetDirection(1);
  murat::m_trk->SetGeneratorCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_dep(int PdgCode = 12) {
//-----------------------------------------------------------------------------
// configure analysis module to handle positrons 
// generated by SingleParticleReactionGun (28)
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockDep");
  murat::m_trk->SetTrackStrawHitBlockName("TrackHitBlockDep");
  murat::m_trk->SetPdgCode(PdgCode);
  murat::m_trk->SetDirection(1);
  murat::m_trk->SetGeneratorCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_dpp() {
//-----------------------------------------------------------------------------
// configure analysis module to handle positrons 
// generated by SingleParticleReactionGun (28)
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockDpp");
  murat::m_trk->SetTrackStrawHitBlockName("TrackHitBlockDpp");
  murat::m_trk->SetPdgCode(2212);
  murat::m_trk->SetDirection(1);
  murat::m_trk->SetGeneratorCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_ump() {
//-----------------------------------------------------------------------------
// configure analysis module to handle signal muons reconstructed as muons
// generated by SingleParticleReactionGun
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockUmp");
  murat::m_trk->SetPdgCode(-13);
  murat::m_trk->SetDirection(-1);
  murat::m_trk->SetGeneratorCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_umm() {
//-----------------------------------------------------------------------------
// configure analysis module to handle signal muons reconstructed as muons
// generated by SingleParticleReactionGun
//-----------------------------------------------------------------------------
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->SetTrackBlockName("TrackBlockUmm");
  murat::m_trk->SetPdgCode(13);
  murat::m_trk->SetDirection(-1);
  murat::m_trk->SetGeneratorCode(28);
}

//-----------------------------------------------------------------------------
void  track_ana_tandip_12(int GeneratorCode = 2) {
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->GetTrackID(0)->SetMinTanDip(1.);
  murat::m_trk->GetTrackID(0)->SetMaxTanDip(2.);
}

//-----------------------------------------------------------------------------
void  val_cpr(int Bit = -1) {
//-----------------------------------------------------------------------------
// configure analysis modules
//-----------------------------------------------------------------------------
  m_vcpr = (TValCalPatRecModule*) g.x->AddModule("TValCalPatRecModule",0);  

  if (Bit != -1) {
    m_vcpr->SetDebugBit(Bit,1);
  }
}


//-----------------------------------------------------------------------------
void  track_debug_tandip_12(int Bit, int GeneratorCode = 2) {
  murat::m_trk = (murat::TTrackAnaModule*) g.x->AddModule("murat::TTrackAnaModule",0);  
  murat::m_trk->GetTrackID(0)->SetMinTanDip(1.);
  murat::m_trk->GetTrackID(0)->SetMaxTanDip(2.);
  murat::m_trk->SetDebugBit(Bit,1);
}

//-----------------------------------------------------------------------------
// GeneratorCode= 2:ConversionElectronGun 28:ParticleGun
//-----------------------------------------------------------------------------
void  track_comp(int PDGCode=11, int GeneratorCode=28, int DebugBit = -1, double XMin=1,double XMax = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetPdgCode      (PDGCode);
  murat::m_tcm->SetGeneratorCode(GeneratorCode);
  if (DebugBit >= 0) {
    murat::m_tcm->SetDebugBit(DebugBit,1);
    if (XMin < XMax) murat::m_tcm->SetDebugCut(DebugBit,XMin,XMax);
  }
}

//-----------------------------------------------------------------------------
// GeneratorCode= 2:ConversionElectronGun 28:ParticleGun
//-----------------------------------------------------------------------------
void  track_comp_old(int PDGCode=11, int GeneratorCode=28, int DebugBit = -1, double XMin=1,double XMax = -1) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetTrackBlockName(0,"TrackBlockTpr");
  murat::m_tcm->SetTrackBlockName(1,"TrackBlockCpr");
  murat::m_tcm->SetPdgCode      (PDGCode);
  murat::m_tcm->SetGeneratorCode(GeneratorCode);
  if (DebugBit >= 0) {
    murat::m_tcm->SetDebugBit(DebugBit,1);
    if (XMin < XMax) murat::m_tcm->SetDebugCut(DebugBit,XMin,XMax);
  }
}

//-----------------------------------------------------------------------------
// debug: do not fill histograms, force the debug bit to be defined
//-----------------------------------------------------------------------------
void  track_comp_debug(int PDGCode=11, int GeneratorCode=28, int DebugBit=14) {
//-----------------------------------------------------------------------------
// configure analysis module
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetPdgCode      (PDGCode);
  murat::m_tcm->SetGeneratorCode(GeneratorCode);
  murat::m_tcm->SetFillHistograms(0);
  murat::m_tcm->SetDebugBit(DebugBit,1);
  murat::m_tcm->GetAna()->SetNEventsToReport(50000);
}

//-----------------------------------------------------------------------------
// GeneratorCode= 2:ConversionElectronGun 28:ParticleGun
// TrkRrecoAlg = 0:TrkPatRec    =1:CalPatRec
//-----------------------------------------------------------------------------
void  track_comp_tmva(int PDGCode=11, int GeneratorCode=28, int TrkRecoAlg = 0, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module to write TMVA training trees
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetPdgCode      (11);
  murat::m_tcm->SetGeneratorCode(GeneratorCode);

  murat::m_tcm->SetWriteTmvaTree(TrkRecoAlg);

  if (DebugBit >= 0) murat::m_tcm->SetDebugBit(DebugBit,1);
}

//-----------------------------------------------------------------------------
// GeneratorCode= 2:ConversionElectronGun 28:ParticleGun
// MVAMode : 100 + Mode (chi2)
//         :       Mode (logfcons)
//-----------------------------------------------------------------------------
void  track_comp_use_mva(int PDGCode=11, int GeneratorCode=28, int TprMvaType = -1, int CprMvaType = 202, 
			 int DebugBit = -1, double XMin=1,double XMax = -1) {
//-----------------------------------------------------------------------------
// configure analysis module to write TMVA training trees
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetPdgCode      (11);
  murat::m_tcm->SetGeneratorCode(GeneratorCode);

  if (TprMvaType >= 0) murat::m_tcm->SetMVA("trkpatrec","e11s5731",TprMvaType);
  if (CprMvaType >= 0) murat::m_tcm->SetMVA("calpatrec","e11s5731",CprMvaType);

  if (DebugBit >= 0) {
    murat::m_tcm->SetDebugBit(DebugBit,1);
    if (XMin < XMax) murat::m_tcm->SetDebugCut(DebugBit,XMin,XMax);
  }
}


//-----------------------------------------------------------------------------
//
//-----------------------------------------------------------------------------
void  rmc_ana(double KMax = 90, int DebugBit = -1) {
//-----------------------------------------------------------------------------
// configure analysis module to write TMVA training trees
//-----------------------------------------------------------------------------
  murat::m_tcm = (murat::TTrackCompModule*) g.x->AddModule("murat::TTrackCompModule",0);  
  murat::m_tcm->SetPdgCode      (-11);
  murat::m_tcm->SetGeneratorCode(41);

  murat::m_tcm->SetKMaxRMC(KMax);

  if (DebugBit >= 0) murat::m_tcm->SetDebugBit(DebugBit,1);
}

