#!/usr/bin/env python
#
#
# $Id: SConscript,v 1.2 2014/01/28 22:39:54 murat Exp $
# $Author: murat $
# $Date: 2014/01/28 22:39:54 $
#
# Original author Rob Kutschke.
#
#------------------------------------------------------------------------------
import os, copy
Import('murat_env')
Import('stntuple_helper')
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
def local_build():
    local_env = murat_env.Clone();
    rootlibs  = local_env['ROOTLIBS']

    if ( not ("EG"    in rootlibs)): rootlibs.insert(rootlibs.index("Physics")+1,"EG");
    if ( not ("TMVA"  in rootlibs)): rootlibs.append("TMVA");

    helper = stntuple_helper(local_env);

    helper.handle_dictionaries();

    skip_list = []

    stntuple_libs = [ 'Stntuple_val', 'Stntuple_alg', 'Stntuple_loop',
                      'Stntuple_obj', 'Stntuple_geom', 'Stntuple_base'
                  ];

    mc_libs = []

    if (os.getenv("STNTUPLE_MC_GEN") != None): mc_libs = ["mc_photos", "mc_base"];

    libs          = stntuple_libs + mc_libs + [
        rootlibs
    ];

    list_of_cc_files = Glob('*.cc',strings=True);
    helper.build_libs(list_of_cc_files,skip_list,libs);

#------------------------------------------------------------------------------
# done, end of murat_pet()
#------------------------------------------------------------------------------
if (os.getenv("BUILD_PET") != None):
    local_build()
