#!/usr/bin/env python
#
# Script to build the files found in this directory.
#------------------------------------------------------------------------------
import os
Import('env')
Import('stntuple_helper')

helper = stntuple_helper(env);
#------------------------------------------------------------------------------
# 2016-10-10: STNTUPLE link: add ROOT 'EG' library after 'Physics' library
#------------------------------------------------------------------------------
rootlibs = env['ROOTLIBS']
if ( not ("EG" in rootlibs)):
    rootlibs.insert(rootlibs.index("Physics")+1,"EG");

helper.handle_dictionaries();

list_of_fortran_files = Glob('*.f',strings=True);
list_of_cc_files      = Glob('*.cc',strings=True);
skip_list             = ["plot_ejected_proton_spectrum.cc"]
libs                  = ['Stntuple_val', 'Stntuple_alg', rootlibs, 'gfortran'];

helper.compile_fortran(list_of_fortran_files,skip_list);

helper.build_libs(list_of_cc_files,skip_list,libs);
# print "tmpdir:"+env['TMP_LIB_DIR']
