#!/bin/bash
# echo pwd  `pwd`
#------------------------------------------------------------------------------
# make sure Stntuple build_config is executed
#------------------------------------------------------------------------------
base=$MUSE_WORK_DIR/build

echo murat::build_config_muse:000: MU2E_VERBOSE:.$MU2E_VERBOSE.
echo murat::build_congig_muse:001: pwd=`pwd`

pushd $MUSE_WORK_DIR ; Stntuple/scripts/build_config_muse ; popd ;
#------------------------------------------------------------------------------
# 'murat' and its subpackages, excluding Stntuple
#------------------------------------------------------------------------------
# pkg=`pwd | awk -F / '{print $(NF-1)}'`
pkg=`echo $0 | awk -F / '{print $(NF-2)}'`

echo "murat::build_congig_muse:002: pwd="`pwd`   pkg=$pkg

pkg_include_dir=$base/include/$pkg

if [ ! -d $pkg_include_dir ] ; then
    echo pkg::build_config_muse: pwd=$pwd ; creating $base/include/$pkg
    mkdir -p $pkg_include_dir
fi

for d in alg ana gaas gui mod obj limits mclimit plot pet petr tdr; do
    if [ ! -e $pkg_include_dir/$d ] ; then 
	cmd="ln -s ../../../$pkg/$d/$d $pkg_include_dir/$d"
	echo `pwd`$0 : executing: $cmd
	$cmd
    fi
done

#------------------------------------------------------------------------------
# murat/Stntuple and its subpackages
#------------------------------------------------------------------------------
# if [ ! -d ../$dir/Stntuple ] ; then mkdir -p ../$dir/Stntuple ; fi
# 
# # for d in alg base gui loop mod obj val ; do
# for d in alg base loop mod obj val ; do
#     if [ ! -e ../$dir/Stntuple/$d ] ; then 
# 	echo `pwd`$0 : creating symbolic link ../$dir/Stntuple/$d
# 	ln -s ../../murat/Stntuple/$d/$d ../$dir/Stntuple/$d
#     fi
# done
