#!/bin/bash
#------------------------------------------------------------------------------
# call format:
#       check_grid_output mdc2018_stntuple.721_0001.flatmugamma.read_reco_stn 14362951 .
#
# non-empty order : reverse
#------------------------------------------------------------------------------

project=$1
  jobid=$2
  order=$3

stage_dir="/pnfs/mu2e/scratch/users/$USER/workflow/$project/outstage/"`ls /pnfs/mu2e/scratch/users/$USER/workflow/$project/outstage | grep $jobid`;

echo ">>> job output directory:" $stage_dir; 

#exit

nsections=0
n_staging_failures=0
nfailed=0
ntotal=0
nsuccess=0

list_of_subjobs=`ls $stage_dir`


for subdir in $list_of_subjobs ; do

    sdir=$stage_dir/$subdir
    echo ">>> subdirectory        :" $sdir; 

    if [ ".$order" == "." ] ; then list_of_sections=`ls     $sdir`
    else                           list_of_sections=`ls -tr $sdir`
    fi

    for d in $list_of_sections ; do 
#    echo $d
#------------------------------------------------------------------------------
# skip directories corresponding to non-completed sections like '00015.wuue'
# now they contain just one .log file per subdirectory
#------------------------------------------------------------------------------
	nf=`echo $d | awk -F . '{print NF}'` 
	if [ $nf == 1 ] ; then
	    logfile=`ls $sdir/$d/*.log` ;
	    x=`cat $logfile | grep "mu2egrid exit status"`; 
	    if [ ."$x" == "." ] ; then
#------------------------------------------------------------------------------
# no return code - assume staging failure
#------------------------------------------------------------------------------
		n_staging_failures=$((n_staging_failures+1))
	    else
		rc=`echo $x | awk '{print $4}'`
		host=`cat $logfile | grep "Starting on host" | awk '{print $5}'`;
		   y=`cat $logfile | grep "TrigReport Events total"`
		
		printf " %5s : section %-6s was running on %-36s , mu2egrid exit status: %3i $y\n" $nsections $d $host $rc
		
		if [ $rc != 0 ] ; then nfailed=$((nfailed+1)) ; else nsuccess=$((nsuccess+1)) ; fi
	    fi
	    nsections=$((nsections+1))
	else
	    printf " %10s : GRID ERROR, job not completed\n" $d
	fi
	ntotal=$((ntotal+1))
    done
done

echo output of $ntotal sections checked : total of $nsections sections completed \; $nsuccess sections completed successfully \; \
    $n_staging_failures sections had staging failures \; \
    $nfailed sections had the mu2e job failed 
